### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by Hammer459** [Drayux/Tartarus#1]
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Drayux** [comment]
Heya! Are you trying to follow the install under DKMS?

If so, I used the SSH git clone command in there, so if you don't have an SSH key set up for GitHub, you might see this error.

Try running the first line instead as
`git clone https://github.com/Drayux/Tartarus.git ~/tartarus` instead :)

**Comment by Drayux** [comment]
Seeing no further conversation, I'm going to assume that this was the trouble. Closing.
