### ISSUE TITLE
Not understanding the purpose of linapse.py

### ISSUE THREAD

**Issue by SamuelGogarty** [Drayux/Tartarus#2]
Hello, I am trying to see how I can reconfigure the key mapping now that the driver is installed.

The closest hint as to how I can do this is by possibly running linapse.py with super user privileges?

When I attempt this, there is no output or window of any sort:

![image](https://github.com/user-attachments/assets/07fd1371-5aa8-49e9-b16e-5f5e17833921)

Is this as intended? if so how should i go about remapping keys?

If not, what can be some possible solutions to this?

Thinking that this was failing to create a window, since im using wayland, i tried again in i3 (x11). This has similar behavior, except my mouse changes into a sort of "+" and i can highlight things on screen, and when i do so, the script exits with some errors.

**Comment by Drayux** [comment]
Greetings! Truth be told this project is only about 90% done, I've neglected completing some of the finer details, and I fear that you may have encountered this trouble as a result of that.

Your assertion is correct, however! Running linapse.py standalone should create a window. Seeing that it is not, I struggle to guess the trouble without more information, but I'm happy to help troubleshoot! 

Do you have tk installed? I see a directory for it in the your linapse folder, which is not the standard location. Tk is the Python windowing library. I have mine installed via my package repository (simply called `tk` for Arch-based distros.) But it can also be installed via pip if you prefer that.

**Comment by SamuelGogarty** [comment]
I went ahead and installed tk via pacman and tried again: 

![image](https://github.com/user-attachments/assets/619f4719-9f31-40e8-ab29-55f301670321)


However there is still no window opening, if there is any more information I can share to help figure out why this is, please let me know.

Thanks for the help.

**Comment by Drayux** [comment]
Hey again! Forgive my untimely reply, had quite a bit on the mind lately!
My first instinct for troubleshooting this would be to try to generate a barebones Tk window to try and deduce if this might be a problem with Linapse or Tk itself.

The following code should create a empty window via the Tk interface.
```py
import tkinter
base = tkinter.Tk()
base.mainloop()
```

![image](https://github.com/user-attachments/assets/3383f653-a95e-41f2-ba2b-a415abdabd0d)

If you put that in a file, I called mine `tktest.py` and then run `python tktest.py`, what do you see?

**Comment by SamuelGogarty** [comment]
Good morning @Drayux, it seems i am able to run this test script just fine, a blank white window pops up as can be seen below:

![image](https://github.com/user-attachments/assets/293bf4e8-9d4a-409c-bd75-f868ef158e22)

**Comment by Drayux** [comment]
This is certainly not what I expected, so I must apologize that my responses seem much moreso posing questions than offering a wealth of knowledge on the matter hahah.

A couple more things come to mind. Inside if your linapse directory, I see entries for io, os, sys, and tk. Do you recall where those came from? In short, none of them should have ended up there from the installation, so I'm wondering if the python interpreter is attempting to use some tk that it found in the relative directory.

So I'm tempted to suggest that you re-clone the repo to another directory...perhaps a ~/tartarus-tmp (totally your call, just so I have an example path to reference) and then to try running linapse.py from that fresh clone, and seeing if that gives you any luck.

If that still doesn't change anything, linapse also provides a CLI. This can give me an indication if it's reading the sysfs file correctly.

Running `python linapse.py -v` should show the current profile, and shouldn't require sudo.
![image](https://github.com/user-attachments/assets/52937556-b8a2-477c-a8b1-3a1636b85ac6)

Fingers are crossed on this one! Thank you for your patience on this one!

**Comment by SamuelGogarty** [comment]
I am not sure how those directories got there, but i did as you suggested and recloned, the python script is now working and i get the window working. 

Thank you for the help
